package sistemarbcks;

import gerenciadordebancodedados.Gerenciador;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema_RBC.SistemaRBC_KS;

public class InterfacePrincipal extends javax.swing.JFrame {
    
    Gerenciador gerenciador = new Gerenciador();
    
    Projeto novoProjeto = new Projeto();
    
    public InterfacePrincipal() {
        initComponents();    
        inicializaValores();
    }
    
    
    final void inicializaValores(){
        ArrayList<String> aux;
                
        //Categorias
        jComboCategoria.removeAllItems();
        aux  = gerenciador.getCategorias();
        for(int i = 0;i<aux.size();i++){
            jComboCategoria.addItem(aux.get(i));
        }
        
        //Moedas
        jComboMoeda.removeAllItems();
        aux  = gerenciador.getMoedas();
        for(int i = 0;i<aux.size();i++){
            jComboMoeda.addItem(aux.get(i));
        }
        
        //Países
        jComboPais.removeAllItems();
        aux  = gerenciador.getPaises();
        for(int i = 0;i<aux.size();i++){
            jComboPais.addItem(aux.get(i));
        }            
        
        //Defini data final
        Date dataFim = new Date();        
        dataFim.setMonth(dataFim.getMonth() + 1);
        dataFim.setYear(dataFim.getYear() + 2);
        
        jTextNomeProjeto.setText("Projeto Teste");
        jTextDataInicio.setValue(new Date());
        jTextDataFim.setValue(dataFim);
        jTextObjetivo.setValue(8000.00);
        jComboCategoria.setSelectedIndex(1);
        jComboPais.setSelectedIndex(21);
    }
    
    private double getValorDouble(String valor){
        String valor_convertido = valor;
        
        //Variável utilizada para converter string em double
        valor_convertido = valor.replace(".", "");
        valor_convertido = valor_convertido.replace(",", ".");
        
        return Double.parseDouble(valor_convertido);
    }
    
    private boolean valida_campos(){
        
        if(jTextNomeProjeto.getText().equals("")){
            return false;
        }                
        
        try{
            
            if(getValorDouble(jTextObjetivo.getText()) <= 0){
                return false;
            }
            
            Date data_inicial = (Date) jTextDataInicio.getValue();
            Date data_final = (Date) jTextDataFim.getValue();
            
            long diferencaDias = (data_final.getTime() - data_inicial.getTime()) / (1000 * 60 * 60 * 24);
            if(diferencaDias < 0){
                return false;
            }
            
        } catch (Exception e){
            return false;
        }
        
        return true;
    }
    
    
    
    private void getAtributosProjeto(){
        String sigla_moeda = gerenciador.getSiglaMoeda(jComboMoeda.getItemAt(jComboMoeda.getSelectedIndex()));
        String sigla_pais = gerenciador.getSiglaPais((String) jComboPais.getSelectedItem());                
        
        novoProjeto.setNome(jTextNomeProjeto.getText());
        novoProjeto.setCategoria(jComboCategoria.getItemAt(jComboCategoria.getSelectedIndex()));
        novoProjeto.setObjetivo(getValorDouble(jTextObjetivo.getText()));
        novoProjeto.setInicio_projeto((Date) jTextDataInicio.getValue());
        novoProjeto.setFim_projeto((Date) jTextDataFim.getValue());
        novoProjeto.setMoeda(sigla_moeda);
        novoProjeto.setPais(sigla_pais);                
        novoProjeto.calculaDiferencaDias();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNomeProjeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboCategoria = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jTextDataInicio = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextDataFim = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboMoeda = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jComboPais = new javax.swing.JComboBox<String>();
        jTextObjetivo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonComparar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema RBC");
        setMinimumSize(new java.awt.Dimension(448, 450));
        setPreferredSize(new java.awt.Dimension(448, 450));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(258, 200));

        jLabel1.setText("Nome do Projeto");

        jTextNomeProjeto.setToolTipText("");

        jLabel3.setText("Categoria");

        jComboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCategoria.setSelectedIndex(1);
        jComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Início");

        jTextDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel7.setText("Data Fim");

        jTextDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel5.setText("Moeda");

        jComboMoeda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("País");

        jComboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextObjetivo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jLabel8.setText("Objetivo (USD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboMoeda, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextNomeProjeto)
                            .addComponent(jComboCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jTextDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5))
                                .addGap(0, 141, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButtonComparar.setText("Comparar");
        jButtonComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompararActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonComparar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompararActionPerformed
        if(valida_campos()){        
            SistemaRBC_KS rbc_KS = new SistemaRBC_KS();
            getAtributosProjeto();                
            ArrayList<Projeto> todosProjetos = gerenciador.getProjetos();
            Object tabelaSimilaridade[][] = new Object[todosProjetos.size()][10];
            String[] colunas = {"Nome do Projeto", "Valor Arrecadado (USD)", "Apoiadores", 
                "Status", "Categoria", "Tempo (Dias)", "Moeda", "País", 
                "Objetivo (USD)", "Similaridade com " + novoProjeto.getNome()};            
                       
            int i=0;            
            for (Projeto projeto:todosProjetos) {
                tabelaSimilaridade[i][0] = projeto.getNome();                
                tabelaSimilaridade[i][1] = formatoNumerico(projeto.getValor_arrecadado());
                tabelaSimilaridade[i][2] = formatoNumerico(projeto.getApoiadores());
                tabelaSimilaridade[i][3] = projeto.getStatus();
                tabelaSimilaridade[i][4] = projeto.getCategoria();
                tabelaSimilaridade[i][5] = formatoNumerico(projeto.getDiasDuracao());
                tabelaSimilaridade[i][6] = gerenciador.getNomeMoeda(projeto.getMoeda());
                tabelaSimilaridade[i][7] = gerenciador.getNomePais(projeto.getPais());                
                tabelaSimilaridade[i][8] = formatoNumerico(projeto.getObjetivo());                
                tabelaSimilaridade[i][9] = formatoNumerico(rbc_KS.calculaSimilaridadeProjetos(projeto, novoProjeto));                
                i++;
            }                                                

            DefaultTableModel tabela  = new DefaultTableModel(tabelaSimilaridade, colunas);            
            TabelaSimilaridades similaridades = new TabelaSimilaridades();
            similaridades.setTabela(tabela);            
            similaridades.setVisible(true);        
        } else {
            JOptionPane.showMessageDialog(this, "Os campos devem estar preenchidos corretamente. \n Por favor verifique!", "Campos Inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCompararActionPerformed

    private String formatoNumerico(double valor) {
        NumberFormat formato = NumberFormat.getInstance();
        formato.setMinimumFractionDigits(2);
        formato.setMaximumFractionDigits(2);
        return formato.format(valor);
    }        
    
    private void jComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComparar;
    private javax.swing.JComboBox<String> jComboCategoria;
    private javax.swing.JComboBox<String> jComboMoeda;
    private javax.swing.JComboBox<String> jComboPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField jTextDataFim;
    private javax.swing.JFormattedTextField jTextDataInicio;
    private javax.swing.JTextField jTextNomeProjeto;
    private javax.swing.JFormattedTextField jTextObjetivo;
    // End of variables declaration//GEN-END:variables
}
